# mongo-express is accessible via http://mongo-express-STACK_NAME.localhost .
# By default, `STACK_NAME` is the directory name, so `mongodb` in this case:
# http://mongo-express-mongodb.localhost . Likewise, the traefik dashboard is
# at http://traefik-mongodb.localhost

version: "3.5"

volumes:
  mongo-conf:
  mongo-data:

services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    image: mongo
    volumes:
      - mongo-conf:/data/configdb
      - mongo-data:/data/db
  mongo-express:
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      # ME_CONFIG_MONGODB_ENABLE_ADMIN: false
      # ME_CONFIG_MONGODB_AUTH_DATABASE:
      # ME_CONFIG_MONGODB_AUTH_USERNAME: ${ME_CONFIG_MONGODB_AUTH_USERNAME}
      # ME_CONFIG_MONGODB_AUTH_PASSWORD: ${ME_CONFIG_MONGODB_AUTH_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
    image: mongo-express
    labels:
      traefik.http.services.mongo-express.loadbalancer.server.port: 8081
    # ports:
    #   - 8080:8081
    # mongo-express fails if it can't reach mongo immediately
    restart: on-failure:5
  traefik:
    image: traefik
    labels:
      traefik.http.routers.traefik-http.service: api@internal
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
