# phpmyadmin is accessible via http://phpmyadmin-STACK_NAME.localhost . By
# default, `STACK_NAME` is the directory name, so `mariadb` in this case:
# http://phpmyadmin-mariadb.localhost . Likewise, the traefik dashboard is at
# http://traefik-mariadb.localhost

version: "3.5"

volumes:
  mariadb-data:

services:
  mariadb:
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
    image: mariadb:latest
    volumes:
      - mariadb-data:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    image: phpmyadmin/phpmyadmin
    # ports:
    #   - 8080:80
  traefik:
    image: traefik
    labels:
      traefik.http.routers.traefik-http.service: api@internal
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
