# phpmyadmin        -> http://phpmyadmin.localhost
# traefik dashboard -> http://traefik.localhost

volumes:
  mariadb-data:

services:
  mariadb:
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
    image: mariadb:latest
    volumes:
      - mariadb-data:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    image: phpmyadmin
    labels:
      traefik.http.services.phpmyadmin.loadbalancer.server.port: 80
      traefik.http.routers.phpmyadmin-http.rule: Host(`phpmyadmin.localhost`)
    ports:
      - 8080:80
  traefik:
    image: traefik
    labels:
      traefik.http.routers.traefik-http.service: api@internal
      traefik.http.routers.traefik-http.rule: Host(`traefik.localhost`)
      traefik.http.services.traefik.loadbalancer.server.port: 8080
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
