version: "3.5"

volumes:
  redis-data:

services:
  redis:
    container_name: redis
    image: redis
    volumes:
      - redis-data:/data
  redis-commander:
    container_name: redis-commander
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: local:redis:6379
    image: ghcr.io/joeferner/redis-commander
      - 8080:8081
    restart: on-failure:5
